site_name: FEM Course Prof. JÃ¤ger
site_url: https://jaegeste.github.io/fem-course

theme:
  name: material
  custom_dir: overrides
  language: de
  logo: media/logo/hfu_logo.svg
  favicon: media/logo/hfu_logo.svg
  palette:
    primary: green
    accent: light green
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - navigation.top
    - content.code.copy
    - content.tabs.link


extra_css:
  - overrides/main.css
  - overrides/extra.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - attr_list
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.plot.ly/plotly-2.35.2.min.js
  - js/plotly-init.js

plugins:
  - search
  - mkdocs_quiz
  - glightbox:
      touchNavigation: true
      loop: false
      zoomable: true
      width: 90vw    # Viewport-Breite statt 90 Prozent
      height: auto   
      slide_effect: "fade"
      draggable: true
  - bibtex:
      bib_file: "literatur.bib"
  - i18n:
      docs_structure: suffix
      languages:
        - locale: de
          name: ðŸ‡©ðŸ‡ª Deutsch
          build: true
          default: true
          nav:
            - Startseite: index.md
            - EinfÃ¼hrung: 01_einfuehrung.md
            - Installation und erste Schritte: 02_installation_erste_schritte.md
            - Modul 1 Kragbalken: 03_kragbalken.md
            - Modul 2 Kerbwirkung: 04_kerbwirkung.md
            - Modul 3 Elementtypen/Ansatzfunktionen: 05_elementtypen_ansatzf.md
            - Modul 4 Krafteinleitung: 06_krafteinleitung.md
            - Modul 5 Modellreduktion: 07_symmetrie.md
            - Modul 6 Modalanalyse: 08_modalanalyse.md
            - Ãœbungen: uebungen.md
        - locale: en
          name: ðŸ‡¬ðŸ‡§ English
          build: true
          nav:
            - Home: index.en.md
            - Introduction: 01_einfuehrung.en.md
            - Installation and getting started: 02_installation_erste_schritte.en.md
            - Module 1 Cantilever Beam: 03_kragbalken.en.md
            - Module 2 Stress Concentration: 04_kerbwirkung.en.md
            - Module 3 Element Types/Shape functions: 05_elementtypen_ansatzf.en.md
            - Module 4 Load Application: 06_krafteinleitung.en.md
            - Module 5 Model Reduction: 07_symmetrie.en.md
            - Module 6 Modal Analysis: 08_modalanalyse.en.md
            - Exercises: uebungen.en.md
            - Peer Teaching A1: peer-teaching_A1.md
            - Peer Teaching A2: peer-teaching_A2.md
            - Peer Teaching B1: peer-teaching_B1.md
            - Peer Teaching B2: peer-teaching_B2.md

